version: '3'

services:

  db:
    image: postgres:9.6.18-alpine
    network_mode: bridge
    container_name: db
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=interview
      - POSTGRES_USER=candidate
      - POSTGRES_PASSWORD=java
      - PGPASSWORD=1234
    volumes:
      - ./src/sql/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
    restart: unless-stopped
  user-service:
    network_mode: bridge
    build: .
    container_name: user-service
    expose:
      - 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/interview
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db
